Revert "deps(dev): bump electron from 25.5.0 to 26.0.0 (#910)"
This reverts commit 60741d745210679b356a9020d996729fa2d4489a.

This update introduced a glif wallet provider issue:

> TypeError: Private key not in range [1, n)